version: "3"
services:
  finance-mock-van-db:
    image: mysql:5.7
    container_name: 'finance-mock-van-db'
    platform: linux/amd64
    ports:
      - '10002:3306'
    environment:
      MYSQL_DATABASE: 'finance-mock-van'
      MYSQL_ROOT_PASSWORD: 'local-password-123!'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    volumes:
      - '~/mysql:/var/lib/mysql'
