spring:
  datasource:
    url: jdbc:mysql://localhost:10002/finance-mock-van?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: local-password-123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
